### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by DarioMelo** [TheFakeMateo/RedPlusPlus#34] opened 2017-12-14 15:34 UTC
- Bill has a different palette the second time you visit (first green, then brown)
- Pokeballs don't "glow" when healing at PkCenters
- Couple when defeated say "I just can't win!" xD
- Youngster in Route 11 says line from Nugget Bridge trainers ("I did my best! I have no regrets!")
- Lavender roofs change color to Saffron roofs when entering Route 8
- Girl in Route 12's lookout that gives you TM39 has glitched text
![bgb00001](https://user-images.githubusercontent.com/30637436/33999759-22d425a4-e0ca-11e7-8c1f-58eb189e908d.png)

**Comment by dannye** [comment] 2017-12-15 02:58
I just fixed the player's name in the Route 12 lookout, thanks.

The changing roof color is not really fixable, unless each map is deliberately designed to not have buildings from another map visible from the edge of the current map - at least not on more than one connection per map.

**Comment by TheFakeMateo** [comment] 2017-12-17 04:22
Guess we could special-case the roof pal like the vermillion/saffron route does. Or better yet, assign it the lav roof pal on that route and make sure you can't see the saffron roofs from that route when I eventually remap everything with the new tilesets I can't use yet.

**Comment by TheFakeMateo** [comment] 2017-12-31 11:08
I think I'll give Bill his Gen 2 sprite and assign it a non-random palette. That will fix the issue with Bill.

Pokeballs not glowing is a known bug. Pokered-gbc was lazy and made the last 4 palettes all flash, making one of them a duplicate of the red palette. We planned on using that duplicate palette as a new one to better match some trainer sprites. The plan is to mimic what Gen 2 does, replacing the Berry Tree palette with the Pokeball palette in Pokecenters, and only flashing that one. Just haven't gotten around to it yet.

Flavor text issues I'll look into as well.

Sorry for leaving some of those bugs unaddressed.

**Comment by TheFakeMateo** [comment] 2018-01-27 07:22
Just double checked, the trainer on Route 11 who says "I did my best! I have no regrets!" said that in the original game, its not actually a bug.

**Closed** 2018-01-27 07:24 UTC
