### ISSUE TITLE
Music & sound FX are broken

### ISSUE THREAD

**Issue by jpmac26** [TheFakeMateo/RedPlusPlus#19] opened 2017-06-10 21:03 UTC
I don't really know exactly how to describe it, but several music tracks such as the intro theme and Prof. Oak's lab only play a single audio channel, and are way too slow. Also, several sound FX in battle are broken, such as the player's Pokemon cries, the Tackle attack sound, etc. However, other music tracks and sound effects play just fine. I have tested this in VBA-M v2.0 on Windows, mGBA v0.5.2 (and the latest nightly build) on Windows and Nintendo 3DS, and GameYob on Nintendo 3DS, and they all exhibit this problem. If needed, I can submit an example later today.

**Comment by TheFakeMateo** [comment] 2017-06-10 22:03
Yeah, I really don't know what you're talking about. I'm playing it as I type this, built from the current copy of the source in the /master branch, and there are no audio issues. So you must have done something wrong when compiling it. Did you use the correct version of RGBDS? Last time I checked, the newest version of RGBDS causes errors, but the instructions in INSTALL.md list a version that should still work as intended.

**Comment by dannye** [comment] 2017-06-10 22:03
We cannot recreate this. All audio is working fine.
Did you build the source yourself? Were you using the current master branch?

Were you using a save file which was created when playing a different rom such as plain Red?
Other save files are not compatible with RedPlusPlus, and if you load a corrupt save file, it's possible that it will have bizarre effects such as improperly loading sound data.

**Comment by jpmac26** [comment] 2017-06-10 22:56
Fixed the problem, I was building the latest version of rgbds, since the rest of the romhacks I play use the latest version to compile. Are rgbds versions v0.3.0+ no longer designed to build Gen 1 roms, or is it an issue with the pokered repository's Makefile, etc., which might be fixable?

**Comment by TheFakeMateo** [comment] 2017-06-11 09:31
The newer versions apparently changed the way something works internally, and data is somehow getting put into the wrong places. Apparently vanilla pokered and pokecrystal were designed using behaviour that was apparently unintentional, so the newer sorting algorithm for floating sections broke them in various ways.

I'm not really sure why this is the case unless there are still some hardcoded addresses somewhere, or what it's doing, but yeah. Guess there could be some sections that aren't assigned to a particular bank that need to be, and that's breaking because the new sorting algorithm isn't putting them in the same bank that it was, so data was messing up in the process.

I guess the long and the short of it is that I'm not entirely sure what all specifically would need to be fixed to keep it from breaking on newer versions (aside from hardcoding addresses to store things, which defeats the whole purpose, but it's what was apparently done for pokered and pokecrystal at one point to get around this), but I know it breaks the vanilla repos as well. It wasn't something I did intentionally to be annoying or anything. But either way, glad you got it sorted. I'lll go ahead and close this issue now.

**Closed by TheFakeMateo** 2017-06-11 09:31 UTC
